"""
Bits Budget Dashboard — Visualize where the model spends its bits.
Usage: streamlit run dashboard/bits_budget_dashboard.py

Requires: dashboard/bits_budget_results.json (generated by bits_budget_analysis.py)
"""
import json
import os
import numpy as np
import streamlit as st
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_PATH = os.path.join(PROJECT_ROOT, "dashboard", "bits_budget_results.json")


@st.cache_data
def load_results():
    with open(RESULTS_PATH) as f:
        return json.load(f)


def color_for_loss(loss, vmin=0, vmax=8, fmt="tuple"):
    """Green (low loss) → Yellow → Red (high loss)"""
    t = min(max((loss - vmin) / (vmax - vmin), 0), 1)
    if t < 0.25:
        r, g, b = 0.2, 0.8, 0.2  # green
    elif t < 0.5:
        r, g, b = 0.8, 0.8, 0.2  # yellow
    elif t < 0.75:
        r, g, b = 0.9, 0.5, 0.1  # orange
    else:
        r, g, b = 0.9, 0.2, 0.2  # red
    if fmt == "css":
        return f"rgb({int(r*255)},{int(g*255)},{int(b*255)})"
    return (r, g, b)


def main():
    st.set_page_config(page_title="Bits Budget", layout="wide")
    st.title("Bits Budget Analysis")
    st.caption("Where does the model spend its 1.1826 BPP?")

    if not os.path.exists(RESULTS_PATH):
        st.error(f"Results file not found: {RESULTS_PATH}")
        st.info("Run `bits_budget_analysis.py` on the pod first, then download the JSON.")
        st.stop()

    data = load_results()
    summary = data['summary']

    # =====================================================
    # Overview
    # =====================================================
    st.header("1. Overview")
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Tokens Analyzed", f"{summary['total_tokens']:,}")
    col2.metric("Average Loss", f"{summary['avg_loss']:.4f} nats")
    col3.metric("Approx BPP", f"{summary['avg_bpb_approx']:.4f}")

    # =====================================================
    # Category Breakdown (Treemap-style)
    # =====================================================
    st.header("2. Where Are the Bits Going?")
    st.markdown("Each token costs some bits. These categories show where the total budget is spent.")

    cats = data['category_breakdown']
    cat_names = list(cats.keys())
    cat_pct_bits = [cats[c]['pct_bits'] for c in cat_names]
    cat_pct_tokens = [cats[c]['pct_tokens'] for c in cat_names]
    cat_avg_loss = [cats[c]['avg_loss'] for c in cat_names]
    cat_colors = ['#4CAF50', '#FFC107', '#FF9800', '#F44336']

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Bar chart: % of bits
    bars1 = ax1.barh(cat_names, cat_pct_bits, color=cat_colors)
    ax1.set_xlabel('% of Total Bits')
    ax1.set_title('Bits Budget by Category')
    for bar, pct in zip(bars1, cat_pct_bits):
        ax1.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                f'{pct:.1f}%', va='center')

    # Bar chart: % of tokens
    bars2 = ax2.barh(cat_names, cat_pct_tokens, color=cat_colors)
    ax2.set_xlabel('% of Tokens')
    ax2.set_title('Token Count by Category')
    for bar, pct in zip(bars2, cat_pct_tokens):
        ax2.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                f'{pct:.1f}%', va='center')

    plt.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.markdown("""
    **Key insight:** The *unpredictable* category uses a disproportionate share of bits
    relative to its token count. These are the floor — no model can predict them.
    The *hard but learnable* category is where improvements pay off.
    """)

    # =====================================================
    # Loss Distribution Histogram
    # =====================================================
    st.header("3. Loss Distribution")
    hist = data['loss_histogram']
    bins = sorted(hist.keys(), key=lambda x: float(x.split('-')[0]))
    counts = [hist[b] for b in bins]
    bin_centers = [(float(b.split('-')[0]) + float(b.split('-')[1])) / 2 for b in bins]

    fig, ax = plt.subplots(figsize=(12, 4))
    colors = [color_for_loss(bc, fmt="tuple") for bc in bin_centers]
    ax.bar(bin_centers, counts, width=0.2, color=colors)
    ax.set_xlabel('Loss (nats)')
    ax.set_ylabel('Token Count')
    ax.set_title('Per-Token Loss Distribution')
    ax.axvline(x=1.0, color='gray', linestyle='--', alpha=0.5, label='easy/medium boundary')
    ax.axvline(x=3.0, color='gray', linestyle='--', alpha=0.5, label='medium/hard boundary')
    ax.axvline(x=5.0, color='gray', linestyle='--', alpha=0.5, label='hard/unpredictable boundary')
    ax.legend()
    st.pyplot(fig)
    plt.close(fig)

    # =====================================================
    # Highlighted Text View
    # =====================================================
    st.header("4. Highlighted Text (loss = color)")
    st.markdown("**Green** = easy (low loss), **Yellow** = medium, **Orange** = hard, **Red** = very hard")

    if data.get('text_samples'):
        sample_idx = st.selectbox("Sample window", range(len(data['text_samples'])),
                                   format_func=lambda i: f"Window {[0, 100, 500][i] if i < 3 else i}")
        sample = data['text_samples'][sample_idx]

        html_parts = []
        for tok in sample:
            color = color_for_loss(tok['loss'], fmt="css")
            text = tok['token'].replace('▁', ' ').replace('<', '&lt;').replace('>', '&gt;')
            loss_str = f"{tok['loss']:.2f}"
            html_parts.append(
                f'<span style="background-color:{color};padding:1px 2px;margin:0;'
                f'border-radius:2px;font-family:monospace;font-size:14px" '
                f'title="loss={loss_str}">{text}</span>'
            )
        st.markdown(''.join(html_parts), unsafe_allow_html=True)
        st.caption("Hover over tokens to see loss values")

    # =====================================================
    # Position Degradation
    # =====================================================
    st.header("5. Position vs Loss")

    if data.get('position_fine'):
        positions = sorted(data['position_fine'].keys(), key=lambda x: int(x))
        pos_vals = [data['position_fine'][p] for p in positions]
        pos_ints = [int(p) for p in positions]

        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(pos_ints, pos_vals, color='steelblue', linewidth=1.5)
        ax.fill_between(pos_ints, pos_vals, alpha=0.1, color='steelblue')
        ax.set_xlabel('Position in 2048-token window')
        ax.set_ylabel('Average Loss (nats)')
        ax.set_title('Position Degradation — early tokens have less context')
        ax.axhline(y=np.mean(pos_vals), color='red', linestyle='--', alpha=0.3, label=f'mean={np.mean(pos_vals):.3f}')
        ax.legend()
        st.pyplot(fig)
        plt.close(fig)

    # =====================================================
    # Top Expensive Bigrams
    # =====================================================
    st.header("6. Most Expensive Bigrams")
    st.markdown("Bigrams ranked by **total bits spent** (frequency × avg loss)")

    if data.get('top_bigrams'):
        bigrams = data['top_bigrams'][:20]
        labels = [f"{b['prev']} → {b['cur']}" for b in bigrams]
        costs = [b['total_cost'] for b in bigrams]

        fig, ax = plt.subplots(figsize=(12, 6))
        bars = ax.barh(labels[::-1], costs[::-1], color='coral')
        ax.set_xlabel('Total Cost (nats)')
        ax.set_title('Top 20 Bigrams by Total Bits Spent')
        for bar, bg in zip(bars, bigrams[::-1]):
            ax.text(bar.get_width() + 50, bar.get_y() + bar.get_height()/2,
                   f"n={bg['count']}, avg={bg['avg_loss']:.1f}", va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    # =====================================================
    # Entropy Quadrants
    # =====================================================
    st.header("7. Confidence vs Correctness")

    if data.get('entropy_quadrants_pct'):
        eq = data['entropy_quadrants_pct']
        fig, ax = plt.subplots(figsize=(6, 6))

        quad_data = [
            ('Confident\nRight', eq.get('confident_right', 0), '#4CAF50'),
            ('Uncertain\nRight', eq.get('uncertain_right', 0), '#8BC34A'),
            ('Confident\nWrong', eq.get('confident_wrong', 0), '#F44336'),
            ('Uncertain\nWrong', eq.get('uncertain_wrong', 0), '#FF9800'),
        ]

        # 2x2 grid
        for i, (label, pct, color) in enumerate(quad_data):
            row, col = i // 2, i % 2
            rect = plt.Rectangle((col * 0.5, (1 - row) * 0.5 - 0.5), 0.5, 0.5,
                                  facecolor=color, alpha=0.7, edgecolor='white', linewidth=2)
            ax.add_patch(rect)
            ax.text(col * 0.5 + 0.25, (1 - row) * 0.5 - 0.25,
                   f'{label}\n{pct:.1f}%', ha='center', va='center',
                   fontsize=12, fontweight='bold', color='white')

        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xlabel('← Confident          Uncertain →')
        ax.set_ylabel('← Wrong          Right →')
        ax.set_title('Entropy Quadrants')
        ax.set_xticks([])
        ax.set_yticks([])
        st.pyplot(fig)
        plt.close(fig)

        st.markdown("""
        **Confident-wrong** (red) = highest-leverage targets. The model is sure but wrong.
        **Uncertain-wrong** (orange) = needs more capacity or context.
        """)

    # =====================================================
    # Juncture Analysis
    # =====================================================
    st.header("8. Juncture Token Analysis")

    if data.get('juncture_analysis'):
        ja = data['juncture_analysis']
        col1, col2 = st.columns(2)
        col1.metric("After juncture avg loss",
                    f"{ja['after_juncture_avg_loss']:.3f}",
                    delta=f"{ja['after_juncture_avg_loss'] - ja['not_after_juncture_avg_loss']:+.3f} vs non-juncture")
        col2.metric("Word-initial avg loss",
                    f"{ja['word_initial_avg_loss']:.3f}",
                    delta=f"{ja['word_initial_avg_loss'] - ja['not_word_initial_avg_loss']:+.3f} vs non-initial")
        st.markdown(f"Tokens after junctures: **{ja['after_juncture_pct']:.1f}%** of all tokens")

    # =====================================================
    # Most Expensive Individual Tokens
    # =====================================================
    st.header("9. Most Expensive Tokens (by total cost)")

    if data.get('top_costly_tokens'):
        tokens = data['top_costly_tokens'][:15]
        fig, ax = plt.subplots(figsize=(10, 5))
        labels = [t['token'].replace('▁', ' ') for t in tokens]
        costs = [t['total_cost'] for t in tokens]
        colors_t = [color_for_loss(t['avg_loss'], fmt="tuple") for t in tokens]
        bars = ax.barh(labels[::-1], costs[::-1], color=colors_t[::-1])
        ax.set_xlabel('Total Cost (nats)')
        ax.set_title('Top 15 Tokens by Total Bits')
        for bar, tok in zip(bars, tokens[::-1]):
            ax.text(bar.get_width() + 50, bar.get_y() + bar.get_height()/2,
                   f"n={tok['count']}, avg={tok['avg_loss']:.1f}", va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    # =====================================================
    # Improvement Potential Summary
    # =====================================================
    st.header("10. Improvement Potential")

    cats = data['category_breakdown']
    total_nats = summary['avg_loss'] * summary['total_tokens']
    unpredictable_nats = cats.get('unpredictable(5+)', {}).get('pct_bits', 0) / 100 * total_nats
    hard_nats = cats.get('hard_learnable(3-5)', {}).get('pct_bits', 0) / 100 * total_nats
    medium_nats = cats.get('medium(1-3)', {}).get('pct_bits', 0) / 100 * total_nats

    floor_bpp = unpredictable_nats / summary['total_tokens'] / np.log(2) * 0.4104
    improvable_bpp = summary['avg_bpb_approx'] - floor_bpp

    col1, col2, col3 = st.columns(3)
    col1.metric("Current BPP", f"{summary['avg_bpb_approx']:.4f}")
    col2.metric("Floor (unpredictable)", f"{floor_bpp:.4f}")
    col3.metric("Improvable BPP", f"{improvable_bpp:.4f}")

    st.markdown(f"""
    **The theoretical improvement ceiling is ~{improvable_bpp:.3f} BPP.**

    This means going from {summary['avg_bpb_approx']:.4f} to {floor_bpp:.4f} is the absolute limit —
    no model of any size could do better on the unpredictable tokens.

    The target of -0.1 BPP requires recovering {0.1/improvable_bpp*100:.0f}% of the improvable budget.
    """)


if __name__ == "__main__":
    main()
